default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: prayforme_development
  username: prayforme
  password: prayforme

# test:
#   <<: *default
#   database: prayforme_test
#
# production:
#   <<: *default
#   database: prayforme_production
#   username: prayforme
#   password: <%= ENV['PRAYFORME_DATABASE_PASSWORD'] %>
